-- MySQL Script generated by MySQL Workbench
-- 02/18/16 13:22:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `salt` VARCHAR(45) NOT NULL COMMENT '',
  `secret` VARCHAR(45) NOT NULL COMMENT '',
  `peso` DOUBLE NULL COMMENT '',
  `altura` INT NULL COMMENT '',
  `edad` INT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contagios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contagios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contagios` (
  `location` VARCHAR(45) NOT NULL COMMENT '',
  `disease` VARCHAR(45) NOT NULL COMMENT '',
  `level` INT NOT NULL COMMENT '',
  `description` VARCHAR(140) NOT NULL COMMENT '',
  PRIMARY KEY (`location`, `disease`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notificaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notificaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notificaction` (
  `idUsuario` INT NOT NULL COMMENT '',
  `contagiosLocation` VARCHAR(45) NOT NULL COMMENT '',
  `contagiosDisease` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`, `contagiosLocation`, `contagiosDisease`)  COMMENT '',
  INDEX `fk_usuario_has_contagios_contagios1_idx` (`contagiosLocation` ASC, `contagiosDisease` ASC)  COMMENT '',
  INDEX `fk_usuario_has_contagios_usuario_idx` (`idUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_has_contagios_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_contagios_contagios1`
    FOREIGN KEY (`contagiosLocation` , `contagiosDisease`)
    REFERENCES `mydb`.`contagios` (`location` , `disease`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
